# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
