# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='msg',
        ),
    ]
