# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-20 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=250)),
                ('event_date', models.DateTimeField(verbose_name='event date')),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(verbose_name='start date for ticket')),
                ('last_date', models.DateTimeField(verbose_name='last date for ticket')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='Events.Event')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
    ]
